# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lesson13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lesson13

  target 'Lesson13Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lesson13UITests' do
    # Pods for testing
  end
pod 'Alamofire'
pod 'HandyJSON'

end
